# Generated by Django 4.0.4 on 2022-05-31 15:15

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='UploadTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('id_prof', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/fs'), upload_to='')),
            ],
            options={
                'abstract': False,
            },
        )
    ]
