# Generated by Django 4.0.4 on 2022-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('tree_count', models.IntegerField()),
                ('location', models.CharField(max_length=25)),
            ],
        ),
    ]
