# Generated by Django 4.0.4 on 2022-05-20 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SqlRel', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SqlRel.bottle')),
            ],
        ),
        migrations.DeleteModel(
            name='b',
        ),
    ]
