# Generated by Django 4.0.4 on 2022-05-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlRel', '0004_bottle_cap_delete_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=10)),
                ('game_company', models.CharField(max_length=10)),
                ('game_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
