# Generated by Django 4.0.4 on 2022-05-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SqlRel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tes',
        ),
    ]
