# Generated by Django 4.0.4 on 2022-05-01 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one_class_views', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empolyee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='one_class_views.department'),
        ),
    ]
