# Generated by Django 4.0.4 on 2022-05-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_class_views', '0002_alter_empolyee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empolyee',
            old_name='department',
            new_name='department_id',
        ),
    ]
