# Generated by Django 4.0.4 on 2022-05-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one_class_views', '0003_rename_department_empolyee_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empolyee',
            name='department_id',
        ),
        migrations.AddField(
            model_name='empolyee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='one_class_views.department'),
            preserve_default=False,
        ),
    ]
