# Generated by Django 4.0.4 on 2022-05-02 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one_class_views', '0004_remove_empolyee_department_id_empolyee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empolyee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='one_class_views.department'),
        ),
    ]
