# Generated by Django 4.0.4 on 2022-05-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_class_views', '0005_alter_empolyee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_uuid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='empolyee',
            old_name='employee_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='empolyee',
            old_name='employee_uuid',
            new_name='uuid',
        ),
    ]
