# Generated by Django 4.0.4 on 2022-05-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_one',
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='TableTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_one_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_test.tableone')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tableone',
            constraint=models.CheckConstraint(check=models.Q(('data', 'Mindblow')), name='check_data'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='tabletwo',
            order_with_respect_to='table_one_data',
        ),
    ]
