# Generated by Django 4.0.4 on 2022-05-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_test', '0002_tableone_tabletwo_tableone_check_data_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tableone',
            name='check_data',
        ),
        migrations.AddConstraint(
            model_name='tableone',
            constraint=models.CheckConstraint(check=models.Q(('data', 'Mindblow'), _negated=True), name='check_data'),
        ),
    ]
