# Generated by Django 4.0.4 on 2022-05-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_test', '0003_remove_tableone_check_data_tableone_check_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tableone',
            name='check_data',
        ),
    ]
