# Generated by Django 4.0.4 on 2022-05-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoUser', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='DATA_EMPTY', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='DATA_EMPTY', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='DATA_EMPTY', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
